<div style="display:flex; justify-content:center; align-items:center; position:relative;">

  <h2 style="margin:auto; text-align:center;">
    UNIVERSIDAD TÉCNICA DEL NORTE <br>
    Facultad de Ingeniería en Ciencias Aplicadas - FICA
  </h2>

  <img src="https://wstemproject.eu/files/2019/06/logo-UTN-2017-768x768.png"
       width="100px">
</div>

<h4 style="text-align:center;"> CARRERA DE CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL </h4>

<h4 style="text-align:center;"> PROGRAMACIÓN II </h4>

<h4 style="text-align:center;"> Librerías para Ciencia de Datos  </h4>

<h5 style="text-align:right;"> Docente: Ing. Wilson Pérez </h5>
<h5 style="text-align:right;"> Marzo - Septiembre 2026</h5>

***
### 2. Pandas
***

Pandas Pandas es una librería especializada en el manejo y análisis de estructuras de datos.

- Velocidad
- Poco código
- Múltiples formatos de archivos

In [ ]:
import pandas as pd

#### Pandas Series
Es muy parecido a un array de una dimensión (o vector) de NumPy.

- Arreglo unidimensional indexado
- Búsqueda por índice
- Operaciones aritméticas
- Distintos tipos de datos

In [2]:
list = pd.Series(['Pedro','Joana','Angel','Paco'], index=[1,7,10,30])
# Aquí definimos una lista con índices específicos

In [3]:
list

1     Pedro
7     Joana
10    Angel
30     Paco
dtype: object

In [4]:
list[10]

'Angel'

In [5]:
list[1]

'Pedro'

In [ ]:
## Qué resultado?
list[2]

In [8]:
list2 = pd.Series(['Pedro','Joana','Angel','Paco'])
# Por defaul comenzando en 0
list2

0    Pedro
1    Joana
2    Angel
3     Paco
dtype: object

In [10]:
list2[1:3]

1    Joana
2    Angel
dtype: object

#### Pandas DataFrame

Parecido a las estructuras matriciales en NumPy.

- Arreglo de dos dimensiones
- Búsqueda por índice (columnas o filas)
- Distintos tipos de datos
- Tamaño variable

In [13]:
# Se crea un diccionario
dict = {'Jugador':['Alex','Katy','Ana','Jorch'],
 'Altura':[182.0,156.23,162.0,188.0],
 'Puntos':[100,200,50,300]}

dict

{'Jugador': ['Alex', 'Katy', 'Ana', 'Jorch'],
 'Altura': [182.0, 156.23, 162.0, 188.0],
 'Puntos': [100, 200, 50, 300]}

In [14]:
# Se crea un dataframe
df = pd.DataFrame(dict)

df

  Jugador  Altura  Puntos
0    Alex  182.00     100
1    Katy  156.23     200
2     Ana  162.00      50
3   Jorch  188.00     300

In [15]:
df2 = pd.DataFrame(dict, index=[2,3,5,7])

df2

  Jugador  Altura  Puntos
2    Alex  182.00     100
3    Katy  156.23     200
5     Ana  162.00      50
7   Jorch  188.00     300

In [17]:
df.columns

Index(['Jugador', 'Altura', 'Puntos'], dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [21]:
df2.index

Index([2, 3, 5, 7], dtype='int64')

### Leer archivos con Pandas

Descargar el archivo CSV https://static.platzi.com/media/public/uploads/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv.

In [24]:
### Leer archivos CSV desde el directorio local
path = '/Users/wilsonperez/Downloads/archivo.csv'

df2 = pd.read_csv(path, sep=",")
df2

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [26]:
df2.head(3)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction

In [27]:
print(df2.head(3))

                                      Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7
1                        11/22/63: A Novel        Stephen King          4.6
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7

   Reviews  Price  Year        Genre
0    17350      8  2016  Non Fiction
1     2052     22  2011      Fiction
2    18979     15  2018  Non Fiction

In [115]:
### Leer archivos CSV desde el internet

url = 'https://raw.githubusercontent.com/wilsonperezrc/varios/refs/heads/main/archivo.csv'

df = pd.read_csv(url, sep=",")
df.head(3)

KeyboardInterrupt:

In [38]:
url = 'https://raw.githubusercontent.com/lorey/list-of-countries/master/csv/countries.csv'
df_poblacion = pd.read_csv(url, sep=";")
df_poblacion.head(3)

,alpha_2,alpha_3,area,capital,continent,currency_code,currency_name,eqivalent_fips_code,fips,geoname_id,languages,name,neighbours,numeric,phone,population,postal_code_format,postal_code_regex,tld
0,AD,AND,468.0,Andorra la Vella,EU,EUR,Euro,NaN,AN,3041565,ca,Andorra,"ES,FR",20,376,84000,AD###,^(?:AD)*(\d{3})$,.ad
1,AE,ARE,82880.0,Abu Dhabi,AS,AED,Dirham,NaN,AE,290557,"ar-AE,fa,en,hi,ur",United Arab Emirates,"SA,OM",784,971,4975593,NaN,NaN,.ae
2,AF,AFG,647500.0,Kabul,AS,AFN,Afghani,NaN,AF,1149361,"fa-AF,ps,uz-AF,tk",Afghanistan,"TM,CN,IR,TJ,PK,UZ",4,93,29121286,NaN,NaN,.af

##### Cambiar el nombre de los encabezados al leer

In [56]:
path = '/Users/wilsonperez/Downloads/archivo.csv'

df = pd.read_csv(path, sep=',', header=1)
df.head(2)

,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
0,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
1,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction

In [119]:
path = '/Users/wilsonperez/Downloads/archivo.csv'

df = pd.read_csv(path, sep=',', header=0)
df.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [121]:
path = '/Users/wilsonperez/Downloads/archivo.csv'

df = pd.read_csv(path, sep=',', header=0, names=['Titulo','Autor','Rating','Review','Precio','Anio','Genero'])
df.head(2)

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

##### Acceder a datos

In [62]:
df['Titulo']

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...
545         Wrecking Ball (Diary of a Wimpy Kid Book 14)
546    You Are a Badass: How to Stop Doubting Your Gr...
547    You Are a Badass: How to Stop Doubting Your Gr...
548    You Are a Badass: How to Stop Doubting Your Gr...
549    You Are a Badass: How to Stop Doubting Your Gr...
Name: Titulo, Length: 550, dtype: object

In [63]:
df['Autor']

0                      JJ Smith
1                  Stephen King
2            Jordan B. Peterson
3                 George Orwell
4      National Geographic Kids
                 ...
545                 Jeff Kinney
546                 Jen Sincero
547                 Jen Sincero
548                 Jen Sincero
549                 Jen Sincero
Name: Autor, Length: 550, dtype: object

In [65]:
df[['Titulo', 'Autor', 'Anio']]

,Titulo,Autor,Anio
0,10-Day Green Smoothie Cleanse,JJ Smith,2016
1,11/22/63: A Novel,Stephen King,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,2018
3,1984 (Signet Classics),George Orwell,2017
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,2019
...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,2019
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2016
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2017
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2018
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2019

In [66]:
ls = ['Titulo', 'Autor', 'Anio']
df[ls]

,Titulo,Autor,Anio
0,10-Day Green Smoothie Cleanse,JJ Smith,2016
1,11/22/63: A Novel,Stephen King,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,2018
3,1984 (Signet Classics),George Orwell,2017
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,2019
...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,2019
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2016
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2017
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2018
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2019

#### Filtrado con loc y iloc

Navegar por un dataFrame por funciones que permiten filtrar datos de manera más específica

 - .loc
 - .iloc


#### .loc: Filtra según un label

In [67]:
df.loc[:]
# Para poder visualizar todo

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [69]:
df.loc[0:4]
# Filtrar por medio de indices.

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [71]:
df.loc[0:4, ['Titulo', 'Autor']]
# Filtrar a traves de etiquetas. Y de manera indexada.

                                              Titulo                     Autor
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [73]:
# Operación con los valores.
df.loc[:,['Precio']] * 2

     Precio
0        16
1        44
2        30
3        12
4        24
..      ...
545      16
546      16
547      16
548      16
549      16

[550 rows x 1 columns]

In [74]:
# Filtrar con operaciones lógicas.
df.loc[:,['Autor']] == 'JJ Smith'

     Autor
0     True
1    False
2    False
3    False
4    False
..     ...
545  False
546  False
547  False
548  False
549  False

[550 rows x 1 columns]

#### .iloc: Filtrar por índices

In [76]:
# Obtener todos los datos
df.iloc[:]

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [79]:
df.iloc[:,1:3]

                        Autor  Rating
0                    JJ Smith     4.7
1                Stephen King     4.6
2          Jordan B. Peterson     4.7
3               George Orwell     4.7
4    National Geographic Kids     4.8
..                        ...     ...
545               Jeff Kinney     4.9
546               Jen Sincero     4.7
547               Jen Sincero     4.7
548               Jen Sincero     4.7
549               Jen Sincero     4.7

[550 rows x 2 columns]

In [83]:
df.iloc[:2,]

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [84]:
df.iloc[:2,[1,2]]

          Autor  Rating
0      JJ Smith     4.7
1  Stephen King     4.6

In [99]:
df.iloc[[1],[1]]

          Autor
1  Stephen King

In [100]:
df.iloc[1,1]

'Stephen King'

In [102]:
df.iloc[1]

Titulo    11/22/63: A Novel
Autor          Stephen King
Rating                  4.6
Review                 2052
Precio                   22
Anio                   2011
Genero              Fiction
Name: 1, dtype: object

#### Agregar o eliminar datos con Pandas

- pd.drop/ pd.del: Para eliminar
- pd.append: Para Agregar

#### Eliminar

In [103]:
df.drop('Genero', axis=1).head(2)

                          Titulo         Autor  Rating  Review  Precio  Anio
0  10-Day Green Smoothie Cleanse      JJ Smith     4.7   17350       8  2016
1              11/22/63: A Novel  Stephen King     4.6    2052      22  2011

In [125]:
df3 = df.copy()
df3 = df3.drop('Genero', axis=1).head(2)
df3

                          Titulo         Autor  Rating  Review  Precio  Anio
0  10-Day Green Smoothie Cleanse      JJ Smith     4.7   17350       8  2016
1              11/22/63: A Novel  Stephen King     4.6    2052      22  2011

In [129]:
df3 = df.copy()
del df3['Precio']
df3.head(3)

,Titulo,Autor,Rating,Review,Anio,Genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,2018,Non Fiction

In [131]:
# Eliminar Filas
df.drop(0, axis=0).head(2)

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction

In [132]:
df.drop([0,1], axis=0).head(2)

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction

#### Agregar Comunas

In [133]:
import numpy as np

In [135]:
df['Nueva_Columna'] = np.nan

In [137]:
df.head(2)

,Titulo,Autor,Rating,Review,Precio,Anio,Genero,Nueva_Columna
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,NaN
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,NaN

In [138]:
df['Columna2'] = 1
df.head(2)

,Titulo,Autor,Rating,Review,Precio,Anio,Genero,Nueva_Columna,Columna2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,NaN,1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,NaN,1

In [140]:
data = np.arange(0,df.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549])

In [141]:
df['Rango2'] = data

df

,Titulo,Autor,Rating,Review,Precio,Anio,Genero,Nueva_Columna,Columna2,Rango2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,NaN,1,0
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,NaN,1,1
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,NaN,1,2
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,NaN,1,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,NaN,1,4
...,...,...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,NaN,1,545
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,NaN,1,546
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,NaN,1,547
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,NaN,1,548
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,NaN,1,549

#### Agregar Filas

In [149]:
df4 = pd.DataFrame([[1, 2], [3, 4]])
df4

   0  1
0  1  2
1  3  4

In [150]:
df5 = pd.DataFrame([[10, 20], [30, 40]])
df5

    0   1
0  10  20
1  30  40

In [155]:
pd.concat([df4, df5])

    0   1
0   1   2
1   3   4
0  10  20
1  30  40

In [157]:
pd.concat([df4, df5], ignore_index=True)

    0   1
0   1   2
1   3   4
2  10  20
3  30  40

#### Manejo de datos nulos

In [160]:
dict = {
    'Col1':[1,2,3,np.nan],
    'Col2':[4,np.nan,6,7],
    'Col3':['a','b','c',None]
}

df = pd.DataFrame(dict)
df

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [161]:
# Retorna una lista con datos booleanos. True hay valor, False no lo hay.
df.isnull()

    Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [162]:
df.isnull()*1

   Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

##### Sustituir valores nulos por un valor

In [163]:
# Sustituye valores Nulos
df.fillna('Nulo')

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0  Nulo     b
2   3.0   6.0     c
3  Nulo   7.0  Nulo

In [167]:
# Devuelve valores no Nulos
df.dropna()

   Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

#### Filtrado de valores

In [168]:
path = '/Users/wilsonperez/Downloads/archivo.csv'

df = pd.read_csv(path, sep=',', header=0, names=['Titulo','Autor','Rating','Review','Precio','Anio','Genero'])
df.head(2)

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [170]:
df['Anio'] > 2016

0      False
1      False
2       True
3       True
4       True
       ...
545     True
546    False
547     True
548     True
549     True
Name: Anio, Length: 550, dtype: bool

In [173]:
mayor_a_2016 = df['Anio'] > 2016
df[mayor_a_2016]

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
...,...,...,...,...,...,...,...
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [177]:
df[df['Anio']>2016].head(10)

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
13,A Wrinkle in Time (Time Quintet),Madeleine L'Engle,4.5,5153,5,2018,Fiction
26,Astrophysics for People in a Hurry,Neil deGrasse Tyson,4.7,9374,9,2017,Non Fiction
32,Becoming,Michelle Obama,4.8,61133,11,2018,Non Fiction
33,Becoming,Michelle Obama,4.8,61133,11,2019,Non Fiction

In [178]:
df['Genero'] == 'Fiction'

0      False
1       True
2      False
3       True
4      False
       ...
545     True
546    False
547    False
548    False
549    False
Name: Genero, Length: 550, dtype: bool

In [180]:
df[(df['Anio'] > 2016) & (df['Genero'] == 'Fiction')]

,Titulo,Autor,Rating,Review,Precio,Anio,Genero
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
13,A Wrinkle in Time (Time Quintet),Madeleine L'Engle,4.5,5153,5,2018,Fiction
40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344,5,2017,Fiction
...,...,...,...,...,...,...,...
509,To Kill a Mockingbird,Harper Lee,4.8,26234,7,2019,Fiction
529,What Should Danny Do? (The Power to Choose Ser...,Adir Levy,4.8,8170,13,2019,Fiction
534,Where the Crawdads Sing,Delia Owens,4.8,87841,15,2019,Fiction
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction

<div style="text-align:center">
    <img src="https://github.com/wilsonperezrc/varios/blob/main/img/img.p.1.5.1.png?raw=true" alt="Descripción" width="1000">
</div>